### ISSUE TITLE
If user doesn't confirm guess by pressing submit, save the chosen answer as guess

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Server#101]
[As a logged-in user playing singleplayer mode, I want to be able to click on my guess and verify this using the submit button#98](https://github.com/sopra-fs23-group-32/SoPra23_Server/issues/98)

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/34284134ad03db43e695df0f73003b117dc011b9
