### ISSUE TITLE
Bugfix: Users get kicked out of server after a while (User gets deleted)

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Server#133]
Apparently, after a while users get kicked out and the error message shows up "userID does not exist", upon which they have to re-register themselves

**Comment by who1a** [comment]
fixed: https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/520d03f588b4ca08a7f71e363884d0993c28e72c
