### ISSUE TITLE
Design and implement a database schema to store game history records.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#16]

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/9de314510c19945da1fedc634011d72503aa78b1

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/9c06afa8930e7a0652f5a4639b13b0348056a62d
