### ISSUE TITLE
Implement backend APIs to retrieve detailed information for each game history record.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#18]

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/a55c10b2b4a05c37c9aa041663aee1db62fbe181, can get shared game info and the personal game score now, still lacking the labels and answers of the game

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/c2c6d5a4954d4fed143ec31e470327c9b9117593 - DTOs for REST request

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/7d42d9c6d4faf3315d7505114b12d21bf9639046

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/9c06afa8930e7a0652f5a4639b13b0348056a62d
