### ISSUE TITLE
Implement client-side limit of number of game history records displayed on a single page, add scrolling bar, pagination on leaderboard and history

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#19]

**Comment by dominic1712** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/0637d34d84372d6af912e6c834ad78ef4a796475
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/dec307baa2adbc4553df326bf6a5251680a69086
