### ISSUE TITLE
Implement backend APIs and functionality to retrieve, display the scoreboard and answer after clicking on “Submit” button. 

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#54]

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/1a271230c71f0a1ec4c53211cc05799bdf186a7f - add functions in 'GameService' for submitting answers and calculating score.
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/c96d02164bf985389e3bb4d9bd650df81d91e998 - REST request for playing game (submit answer and update score)

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/368da1dd3b581b0de4415714eee83eb8188fad82 @leyixu21
