### ISSUE TITLE
Create UI for "Create a room".

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#58]

**Comment by dominic1712** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/a7222efa848deaef99c7b1319d98ccf6623d100d
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/1a411b99f1a38d2735e2de96fa0683bb51fa92b4
