### ISSUE TITLE
Implement sending, retrieving, storing of overall and category specific rankings.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#78]

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/e9d28d2637e341fa232b21d12d3e00c8e99e2514

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Server/commit/e2676b627edc2fb2cb0cf5fd867b574a68958408
