### ISSUE TITLE
As a logged-in user, I want to be able to choose how many rounds I want to play in the game

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Server#85]
### Acceptance Criteria
- [x]  By clicking on the white text field next to "rounds", you can enter how many rounds you want to play in the game
- [x]  After entering a number, the number fills the white text field, confirming the entry
number
### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#17

**Comment by Dzl666** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/02135446b433f8623074c520cadb81ae688c4f23
